language: java
install: true

addons:
  sonarcloud:
    organization: "wimdeblauwe-github"
    token:
      secure: "ocFte9eeh01dTHVc9dTMj9b5I2sV/XE7t7dW08CGEQf/QC1icj5/kCDIRYelbbFjjUb38pt31NxxvOnzIjQHnKRgQZ6GxxY0ApKHhmdW1px6cUuYyl4saYBzylrVlWaoxLOVEqvBR3x2aHXkc2KCb+PkbGtgLGN6myShK3yZm1JsJdiXhap1haN2jrAWXb4IjGDtgtkMeCYltJJE7UnxoRhpvMsKSnv43YNViGWYi730u/DWpMxidKsKFVvTl2rNHHhJa06ZrmsupY2pGBiYDiVmf3tgQYh+PYxZZAr35wcikBKulZzHdZa+KgHeD70GidjaSlI3XxWgM1M9NOHWvqY5wiKnllSrCIbrIvt2907N4MwyibW3YCkUIy40647QFQgiHKqfgnW10N8/caSxaiPJWPXl4bGAjLEsvQq95RP0ZWuW4FMFs0DbMKoFFmuBUaslfVFXPod6uShBgd4w+hNvzhlbkC27yNb9Fy+gCMjm8vQzVxRkN7hQ8+r3XaRGV0SYous0uGDtW1rBWmCwEdXUHrYBhp3INPMWYPOmbf97BwJmYueNbyrfVL64duFdKmsdEFUZ6dVKx0IU4mrUMvA41QKCA2WvFpc1NaMY23IXex9AvEN5hcbspepASjtNSUTn6WbQ5gGC9pAqIFI5Yn90PCzMpLHcCIZUeBqHjGs="
    branches:
      - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean install sonar:sonar